### ISSUE TITLE
Horizontal scrollbar in sidebar

### ISSUE THREAD

**Issue by ThinkGraphical** [websemantics/pyrocms-theme#1]
I'm noticing a horizontal scroll in the sidemenu, while it looks like the content could fit.

<img width="1444" alt="control_panel_ _posts_and_new_issue_ _websemantics_pyrocms-theme" src="https://cloud.githubusercontent.com/assets/1651789/20458113/564906e6-ae9b-11e6-84fa-1401778fee47.png">

When you remove following fixed width,
the horizontal scroll is gone.
``` 
// line 15 in theme/layout/_sidebar.scss
body:not(.pyrocms) #sidebar .nav {
    margin: 0;
    padding: 0;
    width: 300px;
    list-style: none; 
}
```

**Comment by websemantics** [comment]
Good call, thanks for the PR @ThinkGraphical
