### ISSUE TITLE
Error when defining PYROCMS_SKIN in .env file

### ISSUE THREAD

**Issue by ThinkGraphical** [websemantics/pyrocms-theme#9]
Don't know if this is a issue with PyroCMS or this theme, but my guess is the theme.

When you define PYROCMS_SKIN=[skin] in your .env file.
And go to `/admin/settings/themes/websemantics.theme.pyrocms`,
You can see that this setting is currently locked (which is a good thing),
but when you click 'update' to purge the cache (and rebuild the assets), you get following error:

```
ErrorException in metadata.twig line 16:
An exception has been thrown during the rendering of a template ("Asset [/home/application/apps/kaap/core/websemantics/pyrocms-theme/resources/scss/skin//theme.scss] does not exist!") in "theme::partials/metadata" at line 16.
```

The weird thing is, that the correct skin is selected on the settings page,
but i suspect on submit the selected skin isn't passed through correctly. Because in the DB under 'default_settings_settings' -> 'websemantics.theme.pyrocms::skin' is NULL.

**Comment by websemantics** [comment]
It does seem a Pyro issue however, `setting_value('websemantics.theme.pyrocms::skin')` should return the correct value since it's bound with the `env` and `config` values,
